"""anima service — harness-grade resiliency for a home agent.

An entity that dies with the terminal isn't a companion, it's a demo.
`anima service install` wraps `anima run` in a systemd **user** unit:
auto-start on boot, auto-restart on crash (Restart=on-failure), logs
in the journal. Pure stdlib; the systemctl/loginctl shell-outs are
injectable so tests never touch a real service manager.

    anima service install --root ~/entities/me          # web on by default
    anima service status  --root ~/entities/me
    anima service restart --root ~/entities/me
    anima service stop    --root ~/entities/me
    anima service uninstall --root ~/entities/me

Non-systemd platforms are detected (no systemctl on PATH) and refused
with a pointer to the manual recipe in README.md.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from typing import Callable, List, Optional

UNIT_DIR = os.path.expanduser("~/.config/systemd/user")

UNIT_TEMPLATE = """\
# Generated by `anima service install` — edit freely; regenerate with
# `anima service install --force`.
[Unit]
Description=ANIMA entity: {name} ({root})
After=network-online.target

[Service]
ExecStart={exec_start}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


# ── pure functions (unit-testable, no systemctl) ─────────────────────

def default_name(root: str) -> str:
    """Service name defaults to the entity root's basename."""
    return os.path.basename(os.path.abspath(root).rstrip(os.sep)) or "anima"


def unit_name(name: str) -> str:
    return f"anima-{name}.service"


def unit_path(name: str, unit_dir: str = UNIT_DIR) -> str:
    return os.path.join(unit_dir, unit_name(name))


def resolve_anima_executable(argv0: Optional[str] = None) -> str:
    """Absolute path of the `anima` console script for ExecStart.

    Prefer how we were invoked (sys.argv[0] when it IS the anima
    script), then PATH lookup; fail loudly rather than write a unit
    that can't start.
    """
    cand = argv0 if argv0 is not None else sys.argv[0]
    if cand and os.path.basename(cand) == "anima":
        path = os.path.abspath(cand)
        if os.path.exists(path) and os.access(path, os.X_OK):
            return path
    found = shutil.which("anima")
    if found:
        return os.path.abspath(found)
    raise RuntimeError(
        "cannot locate the `anima` console script (not invoked as "
        "`anima` and not on PATH) — install with pipx/pip first, or "
        "write the unit by hand (see README.md, Deployment appendix)")


def build_exec_start(anima_path: str, root: str, *,
                     web: bool = True, telegram: bool = False) -> str:
    args: List[str] = [anima_path, "run", "--root", os.path.abspath(root)]
    if web:
        args.append("--web")
    if telegram:
        args.append("--telegram")
    return " ".join(shlex.quote(a) for a in args)


def render_unit(name: str, root: str, exec_start: str) -> str:
    return UNIT_TEMPLATE.format(name=name, root=os.path.abspath(root),
                                exec_start=exec_start)


# ── the shell-out layer (injectable) ─────────────────────────────────

Runner = Callable[..., "subprocess.CompletedProcess"]


def _default_runner(args: List[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True,
                          timeout=60, **kw)


class ServiceManager:
    """systemctl --user lifecycle for anima units.

    `runner` is the single seam to the OS: any callable with the
    subprocess.run(list) -> CompletedProcess shape works, so the test
    suite never launches a real systemctl.
    """

    def __init__(self, *, unit_dir: str = UNIT_DIR,
                 runner: Runner = _default_runner,
                 which: Callable[[str], Optional[str]] = shutil.which,
                 out=None):
        self.unit_dir = unit_dir
        self.runner = runner
        self.which = which
        self.out = out if out is not None else sys.stdout

    # ── helpers ───────────────────────────────────────────────────────
    def _say(self, msg: str) -> None:
        print(msg, file=self.out)

    def require_systemd(self) -> None:
        if not self.which("systemctl"):
            raise RuntimeError(
                "systemd not found (no systemctl on PATH) — `anima "
                "service` manages systemd user units only. On this "
                "platform, run `anima run --root <root> --web` under "
                "your own supervisor; see README.md → 'Deployment "
                "appendix: without systemd' for the manual recipe.")

    def _systemctl(self, *args: str) -> subprocess.CompletedProcess:
        return self.runner(["systemctl", "--user", *args])

    def linger_enabled(self) -> Optional[bool]:
        user = os.environ.get("USER") or os.environ.get("LOGNAME") or ""
        proc = self.runner(["loginctl", "show-user", user,
                            "--property=Linger"])
        if proc.returncode != 0:
            return None  # can't tell — instruct, don't guess
        return "Linger=yes" in (proc.stdout or "")

    def _ensure_linger(self) -> None:
        """Boot-survival needs lingering. Try the non-privileged path;
        if that fails, print the exact command instead of escalating."""
        user = os.environ.get("USER") or os.environ.get("LOGNAME") or ""
        state = self.linger_enabled()
        if state:
            return
        cmd = f"loginctl enable-linger {user}"
        try:
            proc = self.runner(["loginctl", "enable-linger", user])
            if proc.returncode == 0 and self.linger_enabled():
                self._say(f"lingering enabled for {user} (the service "
                          f"now survives logout and starts at boot)")
                return
        except Exception:
            pass
        self._say("⚠ lingering is OFF for your user: the service dies "
                  "at logout and won't start at boot until you run:\n"
                  f"    sudo {cmd}")

    # ── verbs ─────────────────────────────────────────────────────────
    def install(self, root: str, *, name: Optional[str] = None,
                web: bool = True, telegram: bool = False,
                force: bool = False,
                anima_path: Optional[str] = None) -> int:
        self.require_systemd()
        root = os.path.abspath(root)
        if not os.path.exists(os.path.join(root, "identity",
                                           "lineage.log")):
            raise RuntimeError(
                f"no entity root at {root} (identity/lineage.log "
                f"missing) — `anima init {root}` first")
        name = name or default_name(root)
        path = unit_path(name, self.unit_dir)
        if os.path.exists(path) and not force:
            raise RuntimeError(
                f"unit already exists at {path} — `anima service "
                f"install --force` to regenerate, or pick another "
                f"--name")
        exe = anima_path or resolve_anima_executable()
        text = render_unit(name, root,
                           build_exec_start(exe, root, web=web,
                                            telegram=telegram))
        os.makedirs(self.unit_dir, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        self._say(f"wrote {path}")
        for step in (("daemon-reload",),
                     ("enable", "--now", unit_name(name))):
            proc = self._systemctl(*step)
            if proc.returncode != 0:
                raise RuntimeError(
                    f"systemctl --user {' '.join(step)} failed: "
                    f"{(proc.stderr or proc.stdout or '').strip()}")
        self._say(f"{unit_name(name)} enabled and started "
                  f"(Restart=on-failure — it comes back from crashes)")
        self._ensure_linger()
        self._say(f"logs: journalctl --user -u {unit_name(name)} -f")
        return 0

    def _existing(self, root: str, name: Optional[str]) -> str:
        name = name or default_name(root)
        path = unit_path(name, self.unit_dir)
        if not os.path.exists(path):
            raise RuntimeError(
                f"no unit at {path} — `anima service install --root "
                f"{root}` first")
        return name

    def status(self, root: str, *, name: Optional[str] = None) -> int:
        self.require_systemd()
        name = self._existing(root, name)
        proc = self._systemctl("status", "--no-pager", unit_name(name))
        self._say((proc.stdout or "").rstrip())
        if proc.stderr:
            self._say(proc.stderr.rstrip())
        # systemctl status: 0 running, 3 stopped — both are answers
        return 0 if proc.returncode in (0, 3) else proc.returncode

    def stop(self, root: str, *, name: Optional[str] = None) -> int:
        self.require_systemd()
        name = self._existing(root, name)
        proc = self._systemctl("stop", unit_name(name))
        if proc.returncode != 0:
            raise RuntimeError(f"stop failed: "
                               f"{(proc.stderr or '').strip()}")
        self._say(f"{unit_name(name)} stopped (still enabled at boot; "
                  f"`anima service uninstall` to remove)")
        return 0

    def restart(self, root: str, *, name: Optional[str] = None) -> int:
        self.require_systemd()
        name = self._existing(root, name)
        proc = self._systemctl("restart", unit_name(name))
        if proc.returncode != 0:
            raise RuntimeError(f"restart failed: "
                               f"{(proc.stderr or '').strip()}")
        self._say(f"{unit_name(name)} restarted")
        return 0

    def uninstall(self, root: str, *, name: Optional[str] = None) -> int:
        self.require_systemd()
        name = self._existing(root, name)
        self._systemctl("disable", "--now", unit_name(name))
        try:
            os.remove(unit_path(name, self.unit_dir))
        except FileNotFoundError:
            pass
        self._systemctl("daemon-reload")
        self._say(f"{unit_name(name)} disabled and removed")
        return 0
